Implemented evidence codes. Cacher bugfix, response json ClientPayloadError bugfix
Evidence codes are now implemented.

ClientPayloadError: data = await response.json() sometimes cause json() to force read response too soon. Replaced with data = await response.read(), followed by data = json.loads(data).