SSLError bugfix
Error was caused by:

2023-12-01 16:53:56,609 [DEBUG] _make_request: https://rest.uniprot.org:443 "GET /idmapping/uniprotkb/results/5d1fd38c0b919578d053ee8ee1f5dc55d4e868bb?cursor=5bkgcvil0o3fbo&size=500 HTTP/1.1" 200 None

Traceback (most recent call last):
  File "C:\Aljosa\Development\GOReverseLookup\.venv\lib\site-packages\urllib3\response.py", line 710, in _error_catcher
    yield
  File "C:\Aljosa\Development\GOReverseLookup\.venv\lib\site-packages\urllib3\response.py", line 1077, in read_chunked
    self._update_chunk_length()
  File "C:\Aljosa\Development\GOReverseLookup\.venv\lib\site-packages\urllib3\response.py", line 1005, in _update_chunk_length
    line = self._fp.fp.readline()  # type: ignore[union-attr]
  File "C:\Program Files\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Program Files\Python310\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Program Files\Python310\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2548)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Aljosa\Development\GOReverseLookup\.venv\lib\site-packages\requests\models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\Aljosa\Development\GOReverseLookup\.venv\lib\site-packages\urllib3\response.py", line 937, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
  File "C:\Aljosa\Development\GOReverseLookup\.venv\lib\site-packages\urllib3\response.py", line 1065, in read_chunked
    with self._error_catcher():
  File "C:\Program Files\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Aljosa\Development\GOReverseLookup\.venv\lib\site-packages\urllib3\response.py", line 721, in _error_catcher
    raise SSLError(e) from e
urllib3.exceptions.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2548)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Aljosa\Development\GOReverseLookup\tests\no_test_main_model.py", line 34, in <module>
    model.products_perform_idmapping()
  File "C:\Aljosa\Development\GOReverseLookup\src\goreverselookup\Model.py", line 621, in products_perform_idmapping
    idmappings = uniprot_api.idmapping_batch(
  File "C:\Aljosa\Development\GOReverseLookup\src\goreverselookup\web_apis\UniprotApi.py", line 953, in idmapping_batch
    results = get_idmapping_results_search(link, session)
  File "C:\Aljosa\Development\GOReverseLookup\src\goreverselookup\web_apis\UniprotApi.py", line 815, in get_idmapping_results_search
    for i, batch in enumerate(
  File "C:\Aljosa\Development\GOReverseLookup\src\goreverselookup\web_apis\UniprotApi.py", line 859, in get_batch
    batch_response = session.get(batch_url)
  File "C:\Aljosa\Development\GOReverseLookup\.venv\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\Aljosa\Development\GOReverseLookup\.venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Aljosa\Development\GOReverseLookup\.venv\lib\site-packages\requests\sessions.py", line 747, in send
    r.content
  File "C:\Aljosa\Development\GOReverseLookup\.venv\lib\site-packages\requests\models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "C:\Aljosa\Development\GOReverseLookup\.venv\lib\site-packages\requests\models.py", line 824, in generate
    raise RequestsSSLError(e)
requests.exceptions.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2548)